# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Certiport,aPearsonVUEBusiness.CertiportCompass
PackageVersion: 19.0.2.1270
InstallerType: nullsoft
Installers:
- InstallerUrl: https://downloads.certiport.com/admin/CertiportConsole/Compass_Setup.exe
  Architecture: x86
  InstallerSha256: 9E102BA214217565E18B0903468BB85ABE852E0D9F198095B5F4A98B7FFD769E
ManifestType: installer
ManifestVersion: 1.5.0
